//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The container to list all possible conditions for activating the level crossing.
 * 
 * <p>Java class for ActivationCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActivationCondition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}EntityIL"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="delayBySwitchPosition" type="{https://www.railml.org/schemas/3.1}SwitchRelatedDelay" minOccurs="0"/&gt;
 *         &lt;element name="aspectRelatedDelay" type="{https://www.railml.org/schemas/3.1}AspectRelatedLevelCrossingDelay" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="signalDelayTime" type="{https://www.railml.org/schemas/3.1}SignalDelayTime" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="activatedBy" type="{https://www.railml.org/schemas/3.1}ApproachStartingDetector" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="andOr" type="{https://www.railml.org/schemas/3.1}tAndOr" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActivationCondition", propOrder = {
    "delayBySwitchPosition",
    "aspectRelatedDelay",
    "signalDelayTime",
    "activatedBy"
})
public class ActivationCondition
    extends EntityIL
{

    protected SwitchRelatedDelay delayBySwitchPosition;
    protected List<AspectRelatedLevelCrossingDelay> aspectRelatedDelay;
    protected List<SignalDelayTime> signalDelayTime;
    @XmlElement(required = true)
    protected List<ApproachStartingDetector> activatedBy;
    @XmlAttribute(name = "andOr")
    protected TAndOr andOr;

    /**
     * Gets the value of the delayBySwitchPosition property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchRelatedDelay }
     *     
     */
    public SwitchRelatedDelay getDelayBySwitchPosition() {
        return delayBySwitchPosition;
    }

    /**
     * Sets the value of the delayBySwitchPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchRelatedDelay }
     *     
     */
    public void setDelayBySwitchPosition(SwitchRelatedDelay value) {
        this.delayBySwitchPosition = value;
    }

    /**
     * Gets the value of the aspectRelatedDelay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aspectRelatedDelay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAspectRelatedDelay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AspectRelatedLevelCrossingDelay }
     * 
     * 
     */
    public List<AspectRelatedLevelCrossingDelay> getAspectRelatedDelay() {
        if (aspectRelatedDelay == null) {
            aspectRelatedDelay = new ArrayList<AspectRelatedLevelCrossingDelay>();
        }
        return this.aspectRelatedDelay;
    }

    /**
     * Gets the value of the signalDelayTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signalDelayTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignalDelayTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SignalDelayTime }
     * 
     * 
     */
    public List<SignalDelayTime> getSignalDelayTime() {
        if (signalDelayTime == null) {
            signalDelayTime = new ArrayList<SignalDelayTime>();
        }
        return this.signalDelayTime;
    }

    /**
     * Gets the value of the activatedBy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activatedBy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivatedBy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApproachStartingDetector }
     * 
     * 
     */
    public List<ApproachStartingDetector> getActivatedBy() {
        if (activatedBy == null) {
            activatedBy = new ArrayList<ApproachStartingDetector>();
        }
        return this.activatedBy;
    }

    /**
     * Gets the value of the andOr property.
     * 
     * @return
     *     possible object is
     *     {@link TAndOr }
     *     
     */
    public TAndOr getAndOr() {
        return andOr;
    }

    /**
     * Sets the value of the andOr property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAndOr }
     *     
     */
    public void setAndOr(TAndOr value) {
        this.andOr = value;
    }

}
