//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * a minimal stub that merely creates a link between ATP and signals. The ATP state mostly derives from a signal at the entry of the ATP section. In some cases, the state can be a function of the aspect of both entry- and exit-signal. Note the need to include virtual signals where ATP changes the signalled speed. A changed speed is often accompanied by a passive trackside speed sign in order to synchronise wayside speed signalling with cabin speed signalling.
 * Not with railML3.1
 * 
 * <p>Java class for ATPdevice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ATPdevice"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}TrackAsset"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="atpType" type="{https://www.railml.org/schemas/3.1}EntityILref"/&gt;
 *         &lt;element name="device" type="{https://www.railml.org/schemas/3.1}EntityILref"/&gt;
 *         &lt;element name="exitSignal" type="{https://www.railml.org/schemas/3.1}EntityILref" maxOccurs="2"/&gt;
 *         &lt;element name="entrySignal" type="{https://www.railml.org/schemas/3.1}EntityILref" maxOccurs="2"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ATPdevice", propOrder = {
    "atpType",
    "device",
    "exitSignal",
    "entrySignal"
})
public abstract class ATPdevice
    extends TrackAsset
{

    @XmlElement(required = true)
    protected EntityILref atpType;
    @XmlElement(required = true)
    protected EntityILref device;
    @XmlElement(required = true)
    protected List<EntityILref> exitSignal;
    @XmlElement(required = true)
    protected List<EntityILref> entrySignal;

    /**
     * Gets the value of the atpType property.
     * 
     * @return
     *     possible object is
     *     {@link EntityILref }
     *     
     */
    public EntityILref getAtpType() {
        return atpType;
    }

    /**
     * Sets the value of the atpType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityILref }
     *     
     */
    public void setAtpType(EntityILref value) {
        this.atpType = value;
    }

    /**
     * Gets the value of the device property.
     * 
     * @return
     *     possible object is
     *     {@link EntityILref }
     *     
     */
    public EntityILref getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityILref }
     *     
     */
    public void setDevice(EntityILref value) {
        this.device = value;
    }

    /**
     * Gets the value of the exitSignal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exitSignal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExitSignal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getExitSignal() {
        if (exitSignal == null) {
            exitSignal = new ArrayList<EntityILref>();
        }
        return this.exitSignal;
    }

    /**
     * Gets the value of the entrySignal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entrySignal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntrySignal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getEntrySignal() {
        if (entrySignal == null) {
            entrySignal = new ArrayList<EntityILref>();
        }
        return this.entrySignal;
    }

}
