//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Balise complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Balise"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}FunctionalInfrastructureEntity"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" type="{https://www.railml.org/schemas/3.1}tBaliseType" /&gt;
 *       &lt;attribute name="belongsToParent" type="{https://www.railml.org/schemas/3.1}tRef" /&gt;
 *       &lt;attribute name="basedOnTemplate" type="{https://www.railml.org/schemas/3.1}tRef" /&gt;
 *       &lt;attribute name="isBaliseGroup" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="baliseGroupType" type="{https://www.railml.org/schemas/3.1}tBaliseGroupTypeExt" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Balise")
public class Balise
    extends FunctionalInfrastructureEntity
{

    @XmlAttribute(name = "type")
    protected TBaliseType type;
    @XmlAttribute(name = "belongsToParent")
    protected String belongsToParent;
    @XmlAttribute(name = "basedOnTemplate")
    protected String basedOnTemplate;
    @XmlAttribute(name = "isBaliseGroup")
    protected Boolean isBaliseGroup;
    @XmlAttribute(name = "baliseGroupType")
    protected String baliseGroupType;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TBaliseType }
     *     
     */
    public TBaliseType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBaliseType }
     *     
     */
    public void setType(TBaliseType value) {
        this.type = value;
    }

    /**
     * Gets the value of the belongsToParent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBelongsToParent() {
        return belongsToParent;
    }

    /**
     * Sets the value of the belongsToParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBelongsToParent(String value) {
        this.belongsToParent = value;
    }

    /**
     * Gets the value of the basedOnTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasedOnTemplate() {
        return basedOnTemplate;
    }

    /**
     * Sets the value of the basedOnTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasedOnTemplate(String value) {
        this.basedOnTemplate = value;
    }

    /**
     * Gets the value of the isBaliseGroup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsBaliseGroup() {
        return isBaliseGroup;
    }

    /**
     * Sets the value of the isBaliseGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBaliseGroup(Boolean value) {
        this.isBaliseGroup = value;
    }

    /**
     * Gets the value of the baliseGroupType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaliseGroupType() {
        return baliseGroupType;
    }

    /**
     * Sets the value of the baliseGroupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaliseGroupType(String value) {
        this.baliseGroupType = value;
    }

}
