//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * This is the top level element for the common model.
 * 
 * <p>Java class for Common complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Common"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}tElementWithID"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="electrificationSystems" type="{https://www.railml.org/schemas/3.1}ElectrificationSystems" minOccurs="0"/&gt;
 *         &lt;element name="organizationalUnits" type="{https://www.railml.org/schemas/3.1}OrganizationalUnits" minOccurs="0"/&gt;
 *         &lt;element name="speedProfiles" type="{https://www.railml.org/schemas/3.1}SpeedProfiles" minOccurs="0"/&gt;
 *         &lt;element name="positioning" type="{https://www.railml.org/schemas/3.1}PositioningSystems" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Common", propOrder = {
    "electrificationSystems",
    "organizationalUnits",
    "speedProfiles",
    "positioning"
})
public class Common
    extends TElementWithID
{

    protected ElectrificationSystems electrificationSystems;
    protected OrganizationalUnits organizationalUnits;
    protected SpeedProfiles speedProfiles;
    protected PositioningSystems positioning;

    /**
     * Gets the value of the electrificationSystems property.
     * 
     * @return
     *     possible object is
     *     {@link ElectrificationSystems }
     *     
     */
    public ElectrificationSystems getElectrificationSystems() {
        return electrificationSystems;
    }

    /**
     * Sets the value of the electrificationSystems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectrificationSystems }
     *     
     */
    public void setElectrificationSystems(ElectrificationSystems value) {
        this.electrificationSystems = value;
    }

    /**
     * Gets the value of the organizationalUnits property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationalUnits }
     *     
     */
    public OrganizationalUnits getOrganizationalUnits() {
        return organizationalUnits;
    }

    /**
     * Sets the value of the organizationalUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationalUnits }
     *     
     */
    public void setOrganizationalUnits(OrganizationalUnits value) {
        this.organizationalUnits = value;
    }

    /**
     * Gets the value of the speedProfiles property.
     * 
     * @return
     *     possible object is
     *     {@link SpeedProfiles }
     *     
     */
    public SpeedProfiles getSpeedProfiles() {
        return speedProfiles;
    }

    /**
     * Sets the value of the speedProfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpeedProfiles }
     *     
     */
    public void setSpeedProfiles(SpeedProfiles value) {
        this.speedProfiles = value;
    }

    /**
     * Gets the value of the positioning property.
     * 
     * @return
     *     possible object is
     *     {@link PositioningSystems }
     *     
     */
    public PositioningSystems getPositioning() {
        return positioning;
    }

    /**
     * Sets the value of the positioning property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositioningSystems }
     *     
     */
    public void setPositioning(PositioningSystems value) {
        this.positioning = value;
    }

}
