//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The control relation from the controller to a signalBox (interlocking)
 * 
 * <p>Java class for ControlledSignalBox complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ControlledSignalBox"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}EntityIL"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="connectedSignalBox" type="{https://www.railml.org/schemas/3.1}EntityILref"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="extentOfControl" type="{https://www.railml.org/schemas/3.1}tExtentOfControl" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ControlledSignalBox", propOrder = {
    "connectedSignalBox"
})
public class ControlledSignalBox
    extends EntityIL
{

    @XmlElement(required = true)
    protected EntityILref connectedSignalBox;
    @XmlAttribute(name = "extentOfControl")
    protected TExtentOfControl extentOfControl;

    /**
     * Gets the value of the connectedSignalBox property.
     * 
     * @return
     *     possible object is
     *     {@link EntityILref }
     *     
     */
    public EntityILref getConnectedSignalBox() {
        return connectedSignalBox;
    }

    /**
     * Sets the value of the connectedSignalBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityILref }
     *     
     */
    public void setConnectedSignalBox(EntityILref value) {
        this.connectedSignalBox = value;
    }

    /**
     * Gets the value of the extentOfControl property.
     * 
     * @return
     *     possible object is
     *     {@link TExtentOfControl }
     *     
     */
    public TExtentOfControl getExtentOfControl() {
        return extentOfControl;
    }

    /**
     * Sets the value of the extentOfControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExtentOfControl }
     *     
     */
    public void setExtentOfControl(TExtentOfControl value) {
        this.extentOfControl = value;
    }

}
