//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * The danger point defines the position beyond the exit signal up to where a train is likely to be safe.
 * Designed for ETCS modelling.
 * 
 * <p>Java class for DangerPoint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DangerPoint"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}EntityIL"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lastSupervisedSectionBeforeDP" type="{https://www.railml.org/schemas/3.1}EntityILref" minOccurs="0"/&gt;
 *         &lt;element name="situatedAtTrackAsset" type="{https://www.railml.org/schemas/3.1}EntityILref" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="distance" type="{https://www.railml.org/schemas/3.1}tLengthM" /&gt;
 *       &lt;attribute name="releaseSpeed" type="{https://www.railml.org/schemas/3.1}tSpeedKmPerHour" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DangerPoint", propOrder = {
    "lastSupervisedSectionBeforeDP",
    "situatedAtTrackAsset"
})
public class DangerPoint
    extends EntityIL
{

    protected EntityILref lastSupervisedSectionBeforeDP;
    protected EntityILref situatedAtTrackAsset;
    @XmlAttribute(name = "distance")
    protected BigDecimal distance;
    @XmlAttribute(name = "releaseSpeed")
    protected BigDecimal releaseSpeed;

    /**
     * Gets the value of the lastSupervisedSectionBeforeDP property.
     * 
     * @return
     *     possible object is
     *     {@link EntityILref }
     *     
     */
    public EntityILref getLastSupervisedSectionBeforeDP() {
        return lastSupervisedSectionBeforeDP;
    }

    /**
     * Sets the value of the lastSupervisedSectionBeforeDP property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityILref }
     *     
     */
    public void setLastSupervisedSectionBeforeDP(EntityILref value) {
        this.lastSupervisedSectionBeforeDP = value;
    }

    /**
     * Gets the value of the situatedAtTrackAsset property.
     * 
     * @return
     *     possible object is
     *     {@link EntityILref }
     *     
     */
    public EntityILref getSituatedAtTrackAsset() {
        return situatedAtTrackAsset;
    }

    /**
     * Sets the value of the situatedAtTrackAsset property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityILref }
     *     
     */
    public void setSituatedAtTrackAsset(EntityILref value) {
        this.situatedAtTrackAsset = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDistance(BigDecimal value) {
        this.distance = value;
    }

    /**
     * Gets the value of the releaseSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReleaseSpeed() {
        return releaseSpeed;
    }

    /**
     * Sets the value of the releaseSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReleaseSpeed(BigDecimal value) {
        this.releaseSpeed = value;
    }

}
