//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * the tuple of references to the detector and its state plus the level of enforcement
 * 
 * <p>Java class for DetectorAndGivenState complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DetectorAndGivenState"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}AssetAndGivenState"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="relatedDetectorAndState" type="{https://www.railml.org/schemas/3.1}DetectorAndState"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DetectorAndGivenState", propOrder = {
    "relatedDetectorAndState"
})
public class DetectorAndGivenState
    extends AssetAndGivenState
{

    @XmlElement(required = true)
    protected DetectorAndState relatedDetectorAndState;

    /**
     * Gets the value of the relatedDetectorAndState property.
     * 
     * @return
     *     possible object is
     *     {@link DetectorAndState }
     *     
     */
    public DetectorAndState getRelatedDetectorAndState() {
        return relatedDetectorAndState;
    }

    /**
     * Sets the value of the relatedDetectorAndState property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetectorAndState }
     *     
     */
    public void setRelatedDetectorAndState(DetectorAndState value) {
        this.relatedDetectorAndState = value;
    }

}
