//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * list of possible purposes for element grouping
 * 
 * <p>Java class for ElementGroupingTypes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ElementGroupingTypes"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}EntityIL"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="elementGroupType" use="required" type="{https://www.railml.org/schemas/3.1}tGroupingTypesExt" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElementGroupingTypes")
public class ElementGroupingTypes
    extends EntityIL
{

    @XmlAttribute(name = "elementGroupType", required = true)
    protected String elementGroupType;

    /**
     * Gets the value of the elementGroupType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementGroupType() {
        return elementGroupType;
    }

    /**
     * Sets the value of the elementGroupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementGroupType(String value) {
        this.elementGroupType = value;
    }

}
