//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ElemBasedPeriodRule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ElemBasedPeriodRule"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}ShiftablePeriodRule"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="operatingDay" type="{https://www.railml.org/schemas/3.1}OperatingDay" minOccurs="0"/&gt;
 *           &lt;element name="genericOperatingPeriod" type="{https://www.railml.org/schemas/3.1}GenericOperatingPeriodDescription" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElemBasedPeriodRule", propOrder = {
    "operatingDay",
    "genericOperatingPeriod"
})
public class ElemBasedPeriodRule
    extends ShiftablePeriodRule
{

    protected OperatingDay operatingDay;
    protected GenericOperatingPeriodDescription genericOperatingPeriod;

    /**
     * Gets the value of the operatingDay property.
     * 
     * @return
     *     possible object is
     *     {@link OperatingDay }
     *     
     */
    public OperatingDay getOperatingDay() {
        return operatingDay;
    }

    /**
     * Sets the value of the operatingDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatingDay }
     *     
     */
    public void setOperatingDay(OperatingDay value) {
        this.operatingDay = value;
    }

    /**
     * Gets the value of the genericOperatingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link GenericOperatingPeriodDescription }
     *     
     */
    public GenericOperatingPeriodDescription getGenericOperatingPeriod() {
        return genericOperatingPeriod;
    }

    /**
     * Sets the value of the genericOperatingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericOperatingPeriodDescription }
     *     
     */
    public void setGenericOperatingPeriod(GenericOperatingPeriodDescription value) {
        this.genericOperatingPeriod = value;
    }

}
