//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ElementProjectionSymbol complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ElementProjectionSymbol"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}VisualizationBaseElement"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isLocatedAt" type="{https://www.railml.org/schemas/3.1}ProjectionCoordinate"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="externalIconRef" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="orientation" type="{https://www.railml.org/schemas/3.1}tElementProjectionSymbolOrientationExt" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElementProjectionSymbol", propOrder = {
    "isLocatedAt"
})
public class ElementProjectionSymbol
    extends VisualizationBaseElement
{

    @XmlElement(required = true)
    protected ProjectionCoordinate isLocatedAt;
    @XmlAttribute(name = "externalIconRef")
    protected String externalIconRef;
    @XmlAttribute(name = "orientation")
    protected String orientation;

    /**
     * Gets the value of the isLocatedAt property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectionCoordinate }
     *     
     */
    public ProjectionCoordinate getIsLocatedAt() {
        return isLocatedAt;
    }

    /**
     * Sets the value of the isLocatedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectionCoordinate }
     *     
     */
    public void setIsLocatedAt(ProjectionCoordinate value) {
        this.isLocatedAt = value;
    }

    /**
     * Gets the value of the externalIconRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalIconRef() {
        return externalIconRef;
    }

    /**
     * Sets the value of the externalIconRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalIconRef(String value) {
        this.externalIconRef = value;
    }

    /**
     * Gets the value of the orientation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrientation() {
        return orientation;
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrientation(String value) {
        this.orientation = value;
    }

}
