//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnergyRollingstock complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnergyRollingstock"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="requiresPowerLimitation" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="permittedStaticContactForce" type="{https://www.railml.org/schemas/3.1}tForceN" /&gt;
 *       &lt;attribute name="permittedMaxContactForce" type="{https://www.railml.org/schemas/3.1}tForceN" /&gt;
 *       &lt;attribute name="requiresAutomaticDroppingDevice" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="requiredFireCategory" type="{https://www.railml.org/schemas/3.1}tRSFireCategoryType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnergyRollingstock")
public class EnergyRollingstock {

    @XmlAttribute(name = "requiresPowerLimitation")
    protected Boolean requiresPowerLimitation;
    @XmlAttribute(name = "permittedStaticContactForce")
    protected BigDecimal permittedStaticContactForce;
    @XmlAttribute(name = "permittedMaxContactForce")
    protected BigDecimal permittedMaxContactForce;
    @XmlAttribute(name = "requiresAutomaticDroppingDevice")
    protected Boolean requiresAutomaticDroppingDevice;
    @XmlAttribute(name = "requiredFireCategory")
    protected TRSFireCategoryType requiredFireCategory;

    /**
     * Gets the value of the requiresPowerLimitation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequiresPowerLimitation() {
        return requiresPowerLimitation;
    }

    /**
     * Sets the value of the requiresPowerLimitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequiresPowerLimitation(Boolean value) {
        this.requiresPowerLimitation = value;
    }

    /**
     * Gets the value of the permittedStaticContactForce property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPermittedStaticContactForce() {
        return permittedStaticContactForce;
    }

    /**
     * Sets the value of the permittedStaticContactForce property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPermittedStaticContactForce(BigDecimal value) {
        this.permittedStaticContactForce = value;
    }

    /**
     * Gets the value of the permittedMaxContactForce property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPermittedMaxContactForce() {
        return permittedMaxContactForce;
    }

    /**
     * Sets the value of the permittedMaxContactForce property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPermittedMaxContactForce(BigDecimal value) {
        this.permittedMaxContactForce = value;
    }

    /**
     * Gets the value of the requiresAutomaticDroppingDevice property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequiresAutomaticDroppingDevice() {
        return requiresAutomaticDroppingDevice;
    }

    /**
     * Sets the value of the requiresAutomaticDroppingDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequiresAutomaticDroppingDevice(Boolean value) {
        this.requiresAutomaticDroppingDevice = value;
    }

    /**
     * Gets the value of the requiredFireCategory property.
     * 
     * @return
     *     possible object is
     *     {@link TRSFireCategoryType }
     *     
     */
    public TRSFireCategoryType getRequiredFireCategory() {
        return requiredFireCategory;
    }

    /**
     * Sets the value of the requiredFireCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRSFireCategoryType }
     *     
     */
    public void setRequiredFireCategory(TRSFireCategoryType value) {
        this.requiredFireCategory = value;
    }

}
