//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FunctionalInfrastructureEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FunctionalInfrastructureEntity"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}EntityIS"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="designator" type="{https://www.railml.org/schemas/3.1}Designator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="external" type="{https://www.railml.org/schemas/3.1}External" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FunctionalInfrastructureEntity", propOrder = {
    "designator",
    "external"
})
@XmlSeeAlso({
    Line.class,
    OperationalPoint.class,
    SignalIS.class,
    ServiceSection.class,
    DerailerIS.class,
    TrainDetectionElement.class,
    Balise.class,
    TrackGauge.class,
    ElectrificationSection.class,
    WeightLimit.class,
    LoadingGauge.class,
    TrainRadio.class,
    TrainProtectionElement.class,
    SpeedSection.class,
    StoppingPlace.class,
    Track.class,
    Platform.class,
    TrackNode.class,
    KeyLockIS.class,
    RestrictionArea.class,
    TrackBed.class,
    XCrossing.class
})
public abstract class FunctionalInfrastructureEntity
    extends EntityIS
{

    protected List<Designator> designator;
    protected List<External> external;

    /**
     * Gets the value of the designator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the designator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDesignator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Designator }
     * 
     * 
     */
    public List<Designator> getDesignator() {
        if (designator == null) {
            designator = new ArrayList<Designator>();
        }
        return this.designator;
    }

    /**
     * Gets the value of the external property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the external property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link External }
     * 
     * 
     */
    public List<External> getExternal() {
        if (external == null) {
            external = new ArrayList<External>();
        }
        return this.external;
    }

}
