//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The container for the IM specific type definitions.
 * 
 * <p>Java class for GenericIM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenericIM"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}EntityIL"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ownsSetsOfAssets" type="{https://www.railml.org/schemas/3.1}EntityILref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="usesTypes" type="{https://www.railml.org/schemas/3.1}GenericTypes"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericIM", propOrder = {
    "ownsSetsOfAssets",
    "usesTypes"
})
public class GenericIM
    extends EntityIL
{

    protected List<EntityILref> ownsSetsOfAssets;
    @XmlElement(required = true)
    protected GenericTypes usesTypes;

    /**
     * Gets the value of the ownsSetsOfAssets property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ownsSetsOfAssets property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOwnsSetsOfAssets().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getOwnsSetsOfAssets() {
        if (ownsSetsOfAssets == null) {
            ownsSetsOfAssets = new ArrayList<EntityILref>();
        }
        return this.ownsSetsOfAssets;
    }

    /**
     * Gets the value of the usesTypes property.
     * 
     * @return
     *     possible object is
     *     {@link GenericTypes }
     *     
     */
    public GenericTypes getUsesTypes() {
        return usesTypes;
    }

    /**
     * Sets the value of the usesTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericTypes }
     *     
     */
    public void setUsesTypes(GenericTypes value) {
        this.usesTypes = value;
    }

}
