//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Used by TVD section reset strategy that the IM regulates. E.g. reset by sweep allowed, manual reset allowed. Note that the IM can apply different reset strategies to sections. Absence of a strategy implies that reset is not possible.
 * 
 * <p>Java class for GenericResetStrategy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenericResetStrategy"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}EntityIL"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="resetStrategy" use="required" type="{https://www.railml.org/schemas/3.1}tGenericResetStrategyList" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericResetStrategy")
public class GenericResetStrategy
    extends EntityIL
{

    @XmlAttribute(name = "resetStrategy", required = true)
    protected TGenericResetStrategyList resetStrategy;

    /**
     * Gets the value of the resetStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link TGenericResetStrategyList }
     *     
     */
    public TGenericResetStrategyList getResetStrategy() {
        return resetStrategy;
    }

    /**
     * Sets the value of the resetStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGenericResetStrategyList }
     *     
     */
    public void setResetStrategy(TGenericResetStrategyList value) {
        this.resetStrategy = value;
    }

}
