//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeometryCurve complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeometryCurve"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}GeometryEntity"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="beginsInGeometryPoint" type="{https://www.railml.org/schemas/3.1}tElementWithIDref" minOccurs="0"/&gt;
 *         &lt;element name="endsInGeometryPoint" type="{https://www.railml.org/schemas/3.1}tElementWithIDref" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeometryCurve", propOrder = {
    "beginsInGeometryPoint",
    "endsInGeometryPoint"
})
@XmlSeeAlso({
    HorizontalCurve.class,
    GradientCurve.class
})
public abstract class GeometryCurve
    extends GeometryEntity
{

    protected TElementWithIDref beginsInGeometryPoint;
    protected TElementWithIDref endsInGeometryPoint;

    /**
     * Gets the value of the beginsInGeometryPoint property.
     * 
     * @return
     *     possible object is
     *     {@link TElementWithIDref }
     *     
     */
    public TElementWithIDref getBeginsInGeometryPoint() {
        return beginsInGeometryPoint;
    }

    /**
     * Sets the value of the beginsInGeometryPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link TElementWithIDref }
     *     
     */
    public void setBeginsInGeometryPoint(TElementWithIDref value) {
        this.beginsInGeometryPoint = value;
    }

    /**
     * Gets the value of the endsInGeometryPoint property.
     * 
     * @return
     *     possible object is
     *     {@link TElementWithIDref }
     *     
     */
    public TElementWithIDref getEndsInGeometryPoint() {
        return endsInGeometryPoint;
    }

    /**
     * Sets the value of the endsInGeometryPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link TElementWithIDref }
     *     
     */
    public void setEndsInGeometryPoint(TElementWithIDref value) {
        this.endsInGeometryPoint = value;
    }

}
