//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GradientCurve complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GradientCurve"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}GeometryCurve"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="curveType" use="required" type="{https://www.railml.org/schemas/3.1}tGradientCurveType" /&gt;
 *       &lt;attribute name="gradient" type="{https://www.railml.org/schemas/3.1}tGradientPerMille" /&gt;
 *       &lt;attribute name="deltaGradient" type="{https://www.railml.org/schemas/3.1}tGradientPerMille" /&gt;
 *       &lt;attribute name="radius" type="{https://www.railml.org/schemas/3.1}tLengthM" /&gt;
 *       &lt;attribute name="length" type="{https://www.railml.org/schemas/3.1}tLengthM" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GradientCurve")
public class GradientCurve
    extends GeometryCurve
{

    @XmlAttribute(name = "curveType", required = true)
    protected TGradientCurveType curveType;
    @XmlAttribute(name = "gradient")
    protected BigDecimal gradient;
    @XmlAttribute(name = "deltaGradient")
    protected BigDecimal deltaGradient;
    @XmlAttribute(name = "radius")
    protected BigDecimal radius;
    @XmlAttribute(name = "length")
    protected BigDecimal length;

    /**
     * Gets the value of the curveType property.
     * 
     * @return
     *     possible object is
     *     {@link TGradientCurveType }
     *     
     */
    public TGradientCurveType getCurveType() {
        return curveType;
    }

    /**
     * Sets the value of the curveType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGradientCurveType }
     *     
     */
    public void setCurveType(TGradientCurveType value) {
        this.curveType = value;
    }

    /**
     * Gets the value of the gradient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGradient() {
        return gradient;
    }

    /**
     * Sets the value of the gradient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGradient(BigDecimal value) {
        this.gradient = value;
    }

    /**
     * Gets the value of the deltaGradient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDeltaGradient() {
        return deltaGradient;
    }

    /**
     * Sets the value of the deltaGradient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDeltaGradient(BigDecimal value) {
        this.deltaGradient = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRadius(BigDecimal value) {
        this.radius = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLength(BigDecimal value) {
        this.length = value;
    }

}
