//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * This is the top level element for the interlocking model. It is the home of several elements (classes) containing the particular aspects of the information.
 * 
 * <p>Java class for Interlocking complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Interlocking"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="assetsForIL" type="{https://www.railml.org/schemas/3.1}AssetsForIL" minOccurs="0"/&gt;
 *         &lt;element name="controllers" type="{https://www.railml.org/schemas/3.1}Controllers" minOccurs="0"/&gt;
 *         &lt;element name="signalBoxes" type="{https://www.railml.org/schemas/3.1}SignalBoxes" minOccurs="0"/&gt;
 *         &lt;element name="specificIMs" type="{https://www.railml.org/schemas/3.1}GenericIMs" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Interlocking", propOrder = {
    "assetsForIL",
    "controllers",
    "signalBoxes",
    "specificIMs"
})
public class Interlocking {

    protected AssetsForIL assetsForIL;
    protected Controllers controllers;
    protected SignalBoxes signalBoxes;
    protected GenericIMs specificIMs;

    /**
     * Gets the value of the assetsForIL property.
     * 
     * @return
     *     possible object is
     *     {@link AssetsForIL }
     *     
     */
    public AssetsForIL getAssetsForIL() {
        return assetsForIL;
    }

    /**
     * Sets the value of the assetsForIL property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetsForIL }
     *     
     */
    public void setAssetsForIL(AssetsForIL value) {
        this.assetsForIL = value;
    }

    /**
     * Gets the value of the controllers property.
     * 
     * @return
     *     possible object is
     *     {@link Controllers }
     *     
     */
    public Controllers getControllers() {
        return controllers;
    }

    /**
     * Sets the value of the controllers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Controllers }
     *     
     */
    public void setControllers(Controllers value) {
        this.controllers = value;
    }

    /**
     * Gets the value of the signalBoxes property.
     * 
     * @return
     *     possible object is
     *     {@link SignalBoxes }
     *     
     */
    public SignalBoxes getSignalBoxes() {
        return signalBoxes;
    }

    /**
     * Sets the value of the signalBoxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignalBoxes }
     *     
     */
    public void setSignalBoxes(SignalBoxes value) {
        this.signalBoxes = value;
    }

    /**
     * Gets the value of the specificIMs property.
     * 
     * @return
     *     possible object is
     *     {@link GenericIMs }
     *     
     */
    public GenericIMs getSpecificIMs() {
        return specificIMs;
    }

    /**
     * Sets the value of the specificIMs property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericIMs }
     *     
     */
    public void setSpecificIMs(GenericIMs value) {
        this.specificIMs = value;
    }

}
