//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LevelCrossingProtection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LevelCrossingProtection"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="barriers" type="{https://www.railml.org/schemas/3.1}tLevelCrossingProtectionBarrierExt" /&gt;
 *       &lt;attribute name="lights" type="{https://www.railml.org/schemas/3.1}tLevelCrossingProtectionLightsExt" /&gt;
 *       &lt;attribute name="acoustic" type="{https://www.railml.org/schemas/3.1}tLevelCrossingProtectionAcousticExt" /&gt;
 *       &lt;attribute name="hasActiveProtection" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LevelCrossingProtection")
public class LevelCrossingProtection {

    @XmlAttribute(name = "barriers")
    protected String barriers;
    @XmlAttribute(name = "lights")
    protected String lights;
    @XmlAttribute(name = "acoustic")
    protected String acoustic;
    @XmlAttribute(name = "hasActiveProtection")
    protected Boolean hasActiveProtection;

    /**
     * Gets the value of the barriers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarriers() {
        return barriers;
    }

    /**
     * Sets the value of the barriers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarriers(String value) {
        this.barriers = value;
    }

    /**
     * Gets the value of the lights property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLights() {
        return lights;
    }

    /**
     * Sets the value of the lights property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLights(String value) {
        this.lights = value;
    }

    /**
     * Gets the value of the acoustic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcoustic() {
        return acoustic;
    }

    /**
     * Sets the value of the acoustic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcoustic(String value) {
        this.acoustic = value;
    }

    /**
     * Gets the value of the hasActiveProtection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasActiveProtection() {
        return hasActiveProtection;
    }

    /**
     * Sets the value of the hasActiveProtection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasActiveProtection(Boolean value) {
        this.hasActiveProtection = value;
    }

}
