//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A restricted area inside a station which can be controlled from a different controller as the rest of the station
 * 
 * <p>Java class for PermissionZone complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PermissionZone"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}TrackAsset"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="canBeControlledBy" type="{https://www.railml.org/schemas/3.1}EntityILref" maxOccurs="unbounded"/&gt;
 *         &lt;element name="controlledElement" type="{https://www.railml.org/schemas/3.1}EntityILref" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PermissionZone", propOrder = {
    "canBeControlledBy",
    "controlledElement"
})
public class PermissionZone
    extends TrackAsset
{

    @XmlElement(required = true)
    protected List<EntityILref> canBeControlledBy;
    @XmlElement(required = true)
    protected List<EntityILref> controlledElement;

    /**
     * Gets the value of the canBeControlledBy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the canBeControlledBy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCanBeControlledBy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getCanBeControlledBy() {
        if (canBeControlledBy == null) {
            canBeControlledBy = new ArrayList<EntityILref>();
        }
        return this.canBeControlledBy;
    }

    /**
     * Gets the value of the controlledElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controlledElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControlledElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getControlledElement() {
        if (controlledElement == null) {
            controlledElement = new ArrayList<EntityILref>();
        }
        return this.controlledElement;
    }

}
