//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Interlocking specific features of the power supply
 * 
 * <p>Java class for PowerSupplyIL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PowerSupplyIL"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}EntityIL"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="numberOfSimultaneousSwitchingActuators" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="signalVoltageMode" type="{https://www.railml.org/schemas/3.1}tSignalVoltageModes" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PowerSupplyIL")
public class PowerSupplyIL
    extends EntityIL
{

    @XmlAttribute(name = "numberOfSimultaneousSwitchingActuators")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfSimultaneousSwitchingActuators;
    @XmlAttribute(name = "signalVoltageMode")
    protected TSignalVoltageModes signalVoltageMode;

    /**
     * Gets the value of the numberOfSimultaneousSwitchingActuators property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfSimultaneousSwitchingActuators() {
        return numberOfSimultaneousSwitchingActuators;
    }

    /**
     * Sets the value of the numberOfSimultaneousSwitchingActuators property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfSimultaneousSwitchingActuators(BigInteger value) {
        this.numberOfSimultaneousSwitchingActuators = value;
    }

    /**
     * Gets the value of the signalVoltageMode property.
     * 
     * @return
     *     possible object is
     *     {@link TSignalVoltageModes }
     *     
     */
    public TSignalVoltageModes getSignalVoltageMode() {
        return signalVoltageMode;
    }

    /**
     * Sets the value of the signalVoltageMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSignalVoltageModes }
     *     
     */
    public void setSignalVoltageMode(TSignalVoltageModes value) {
        this.signalVoltageMode = value;
    }

}
