//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RTM_IntrinsicCoordinate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTM_IntrinsicCoordinate"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}RTM_BaseObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="linearCoordinate" type="{https://www.railml.org/schemas/3.1}RTM_LinearCoordinate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="geometricCoordinate" type="{https://www.railml.org/schemas/3.1}RTM_GeometricCoordinate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="intrinsicCoord" use="required" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTM_IntrinsicCoordinate", propOrder = {
    "linearCoordinate",
    "geometricCoordinate"
})
public class RTMIntrinsicCoordinate
    extends RTMBaseObject
{

    protected List<RTMLinearCoordinate> linearCoordinate;
    protected List<RTMGeometricCoordinate> geometricCoordinate;
    @XmlAttribute(name = "intrinsicCoord", required = true)
    protected double intrinsicCoord;

    /**
     * Gets the value of the linearCoordinate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linearCoordinate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinearCoordinate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RTMLinearCoordinate }
     * 
     * 
     */
    public List<RTMLinearCoordinate> getLinearCoordinate() {
        if (linearCoordinate == null) {
            linearCoordinate = new ArrayList<RTMLinearCoordinate>();
        }
        return this.linearCoordinate;
    }

    /**
     * Gets the value of the geometricCoordinate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geometricCoordinate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeometricCoordinate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RTMGeometricCoordinate }
     * 
     * 
     */
    public List<RTMGeometricCoordinate> getGeometricCoordinate() {
        if (geometricCoordinate == null) {
            geometricCoordinate = new ArrayList<RTMGeometricCoordinate>();
        }
        return this.geometricCoordinate;
    }

    /**
     * Gets the value of the intrinsicCoord property.
     * 
     */
    public double getIntrinsicCoord() {
        return intrinsicCoord;
    }

    /**
     * Sets the value of the intrinsicCoord property.
     * 
     */
    public void setIntrinsicCoord(double value) {
        this.intrinsicCoord = value;
    }

}
