//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RTM_LinearPositioningSystem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTM_LinearPositioningSystem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}RTM_PositioningSystem"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="anchor" type="{https://www.railml.org/schemas/3.1}RTM_LinearAnchorPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="linearReferencingMethod" use="required" type="{https://www.railml.org/schemas/3.1}tLrsMethod" /&gt;
 *       &lt;attribute name="startMeasure" use="required" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="endMeasure" use="required" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="units" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTM_LinearPositioningSystem", propOrder = {
    "anchor"
})
public class RTMLinearPositioningSystem
    extends RTMPositioningSystem
{

    protected List<RTMLinearAnchorPoint> anchor;
    @XmlAttribute(name = "linearReferencingMethod", required = true)
    protected TLrsMethod linearReferencingMethod;
    @XmlAttribute(name = "startMeasure", required = true)
    protected double startMeasure;
    @XmlAttribute(name = "endMeasure", required = true)
    protected double endMeasure;
    @XmlAttribute(name = "units", required = true)
    protected String units;

    /**
     * Gets the value of the anchor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anchor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnchor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RTMLinearAnchorPoint }
     * 
     * 
     */
    public List<RTMLinearAnchorPoint> getAnchor() {
        if (anchor == null) {
            anchor = new ArrayList<RTMLinearAnchorPoint>();
        }
        return this.anchor;
    }

    /**
     * Gets the value of the linearReferencingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link TLrsMethod }
     *     
     */
    public TLrsMethod getLinearReferencingMethod() {
        return linearReferencingMethod;
    }

    /**
     * Sets the value of the linearReferencingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLrsMethod }
     *     
     */
    public void setLinearReferencingMethod(TLrsMethod value) {
        this.linearReferencingMethod = value;
    }

    /**
     * Gets the value of the startMeasure property.
     * 
     */
    public double getStartMeasure() {
        return startMeasure;
    }

    /**
     * Sets the value of the startMeasure property.
     * 
     */
    public void setStartMeasure(double value) {
        this.startMeasure = value;
    }

    /**
     * Gets the value of the endMeasure property.
     * 
     */
    public double getEndMeasure() {
        return endMeasure;
    }

    /**
     * Sets the value of the endMeasure property.
     * 
     */
    public void setEndMeasure(double value) {
        this.endMeasure = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnits(String value) {
        this.units = value;
    }

}
