//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RTM_LinearAnchorPoint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTM_LinearAnchorPoint"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}RTM_BaseObject"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="anchorName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="measure" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="measureToNext" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTM_LinearAnchorPoint")
public class RTMLinearAnchorPoint
    extends RTMBaseObject
{

    @XmlAttribute(name = "anchorName")
    protected String anchorName;
    @XmlAttribute(name = "measure")
    protected Double measure;
    @XmlAttribute(name = "measureToNext")
    protected Double measureToNext;

    /**
     * Gets the value of the anchorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnchorName() {
        return anchorName;
    }

    /**
     * Sets the value of the anchorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnchorName(String value) {
        this.anchorName = value;
    }

    /**
     * Gets the value of the measure property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMeasure() {
        return measure;
    }

    /**
     * Sets the value of the measure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMeasure(Double value) {
        this.measure = value;
    }

    /**
     * Gets the value of the measureToNext property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMeasureToNext() {
        return measureToNext;
    }

    /**
     * Sets the value of the measureToNext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMeasureToNext(Double value) {
        this.measureToNext = value;
    }

}
