//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RTM_Relation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTM_Relation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}RTM_NetworkResource"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="elementA" type="{https://www.railml.org/schemas/3.1}tElementWithIDref" form="qualified"/&gt;
 *         &lt;element name="elementB" type="{https://www.railml.org/schemas/3.1}tElementWithIDref" form="qualified"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="navigability" type="{https://www.railml.org/schemas/3.1}tNavigability" /&gt;
 *       &lt;attribute name="positionOnA" type="{https://www.railml.org/schemas/3.1}tUsage" /&gt;
 *       &lt;attribute name="positionOnB" type="{https://www.railml.org/schemas/3.1}tUsage" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTM_Relation", propOrder = {
    "elementA",
    "elementB"
})
@XmlSeeAlso({
    NetRelation.class
})
public class RTMRelation
    extends RTMNetworkResource
{

    @XmlElement(required = true)
    protected TElementWithIDref elementA;
    @XmlElement(required = true)
    protected TElementWithIDref elementB;
    @XmlAttribute(name = "navigability")
    protected TNavigability navigability;
    @XmlAttribute(name = "positionOnA")
    protected BigInteger positionOnA;
    @XmlAttribute(name = "positionOnB")
    protected BigInteger positionOnB;

    /**
     * Gets the value of the elementA property.
     * 
     * @return
     *     possible object is
     *     {@link TElementWithIDref }
     *     
     */
    public TElementWithIDref getElementA() {
        return elementA;
    }

    /**
     * Sets the value of the elementA property.
     * 
     * @param value
     *     allowed object is
     *     {@link TElementWithIDref }
     *     
     */
    public void setElementA(TElementWithIDref value) {
        this.elementA = value;
    }

    /**
     * Gets the value of the elementB property.
     * 
     * @return
     *     possible object is
     *     {@link TElementWithIDref }
     *     
     */
    public TElementWithIDref getElementB() {
        return elementB;
    }

    /**
     * Sets the value of the elementB property.
     * 
     * @param value
     *     allowed object is
     *     {@link TElementWithIDref }
     *     
     */
    public void setElementB(TElementWithIDref value) {
        this.elementB = value;
    }

    /**
     * Gets the value of the navigability property.
     * 
     * @return
     *     possible object is
     *     {@link TNavigability }
     *     
     */
    public TNavigability getNavigability() {
        return navigability;
    }

    /**
     * Sets the value of the navigability property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNavigability }
     *     
     */
    public void setNavigability(TNavigability value) {
        this.navigability = value;
    }

    /**
     * Gets the value of the positionOnA property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPositionOnA() {
        return positionOnA;
    }

    /**
     * Sets the value of the positionOnA property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPositionOnA(BigInteger value) {
        this.positionOnA = value;
    }

    /**
     * Gets the value of the positionOnB property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPositionOnB() {
        return positionOnB;
    }

    /**
     * Sets the value of the positionOnB property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPositionOnB(BigInteger value) {
        this.positionOnB = value;
    }

}
