//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpeedProfileLoad complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpeedProfileLoad"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="maxAxleLoad" type="{https://www.railml.org/schemas/3.1}tWeightTons" /&gt;
 *       &lt;attribute name="maxMeterLoad" type="{https://www.railml.org/schemas/3.1}tMeterloadTonsPerMeter" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpeedProfileLoad")
public class SpeedProfileLoad {

    @XmlAttribute(name = "maxAxleLoad")
    protected BigDecimal maxAxleLoad;
    @XmlAttribute(name = "maxMeterLoad")
    protected BigDecimal maxMeterLoad;

    /**
     * Gets the value of the maxAxleLoad property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxAxleLoad() {
        return maxAxleLoad;
    }

    /**
     * Sets the value of the maxAxleLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxAxleLoad(BigDecimal value) {
        this.maxAxleLoad = value;
    }

    /**
     * Gets the value of the maxMeterLoad property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxMeterLoad() {
        return maxMeterLoad;
    }

    /**
     * Sets the value of the maxMeterLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxMeterLoad(BigDecimal value) {
        this.maxMeterLoad = value;
    }

}
