//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpeedProfileTilting complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpeedProfileTilting"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="actuation" type="{https://www.railml.org/schemas/3.1}tTiltingActuationType" /&gt;
 *       &lt;attribute name="maxTiltingAngle" type="{https://www.railml.org/schemas/3.1}tAngleDegQuadrant" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpeedProfileTilting")
public class SpeedProfileTilting {

    @XmlAttribute(name = "actuation")
    protected TTiltingActuationType actuation;
    @XmlAttribute(name = "maxTiltingAngle")
    protected BigDecimal maxTiltingAngle;

    /**
     * Gets the value of the actuation property.
     * 
     * @return
     *     possible object is
     *     {@link TTiltingActuationType }
     *     
     */
    public TTiltingActuationType getActuation() {
        return actuation;
    }

    /**
     * Sets the value of the actuation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTiltingActuationType }
     *     
     */
    public void setActuation(TTiltingActuationType value) {
        this.actuation = value;
    }

    /**
     * Gets the value of the maxTiltingAngle property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxTiltingAngle() {
        return maxTiltingAngle;
    }

    /**
     * Sets the value of the maxTiltingAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxTiltingAngle(BigDecimal value) {
        this.maxTiltingAngle = value;
    }

}
