//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tAirBrakeApplicationDirection.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tAirBrakeApplicationDirection"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="R"/&gt;
 *     &lt;enumeration value="P"/&gt;
 *     &lt;enumeration value="N/A"/&gt;
 *     &lt;enumeration value="G"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tAirBrakeApplicationDirection")
@XmlEnum
public enum TAirBrakeApplicationDirection {


    /**
     * Rapid
     * 
     */
    R("R"),

    /**
     * Passenger
     * 
     */
    P("P"),
    @XmlEnumValue("N/A")
    N_A("N/A"),

    /**
     * Goods
     * 
     */
    G("G");
    private final String value;

    TAirBrakeApplicationDirection(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TAirBrakeApplicationDirection fromValue(String v) {
        for (TAirBrakeApplicationDirection c: TAirBrakeApplicationDirection.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
