//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tBorderType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tBorderType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="tariff"/&gt;
 *     &lt;enumeration value="station"/&gt;
 *     &lt;enumeration value="state"/&gt;
 *     &lt;enumeration value="infrastructureManager"/&gt;
 *     &lt;enumeration value="country"/&gt;
 *     &lt;enumeration value="area"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tBorderType")
@XmlEnum
public enum TBorderType {


    /**
     * border between different tariff zones;
     * Shall also be used for borders between two (or more) transport associations
     * 
     */
    @XmlEnumValue("tariff")
    TARIFF("tariff"),

    /**
     * border of a station
     * 
     */
    @XmlEnumValue("station")
    STATION("station"),

    /**
     * border of a (federal) state
     * 
     */
    @XmlEnumValue("state")
    STATE("state"),

    /**
     * border between infrastructure networks of different infrastructure managers
     * 
     */
    @XmlEnumValue("infrastructureManager")
    INFRASTRUCTURE_MANAGER("infrastructureManager"),

    /**
     * border between different (national) countries
     * 
     */
    @XmlEnumValue("country")
    COUNTRY("country"),

    /**
     * border between different areas, e.g. areas that are controlled by different controllers
     * 
     */
    @XmlEnumValue("area")
    AREA("area");
    private final String value;

    TBorderType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TBorderType fromValue(String v) {
        for (TBorderType c: TBorderType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
