//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tCrossedElementType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tCrossedElementType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="lake"/&gt;
 *     &lt;enumeration value="river"/&gt;
 *     &lt;enumeration value="valley"/&gt;
 *     &lt;enumeration value="ridge"/&gt;
 *     &lt;enumeration value="peak"/&gt;
 *     &lt;enumeration value="road"/&gt;
 *     &lt;enumeration value="motorway"/&gt;
 *     &lt;enumeration value="footway"/&gt;
 *     &lt;enumeration value="city"/&gt;
 *     &lt;enumeration value="area"/&gt;
 *     &lt;enumeration value="cycleway"/&gt;
 *     &lt;enumeration value="railway"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tCrossedElementType")
@XmlEnum
public enum TCrossedElementType {

    @XmlEnumValue("lake")
    LAKE("lake"),
    @XmlEnumValue("river")
    RIVER("river"),
    @XmlEnumValue("valley")
    VALLEY("valley"),
    @XmlEnumValue("ridge")
    RIDGE("ridge"),
    @XmlEnumValue("peak")
    PEAK("peak"),
    @XmlEnumValue("road")
    ROAD("road"),
    @XmlEnumValue("motorway")
    MOTORWAY("motorway"),
    @XmlEnumValue("footway")
    FOOTWAY("footway"),
    @XmlEnumValue("city")
    CITY("city"),
    @XmlEnumValue("area")
    AREA("area"),
    @XmlEnumValue("cycleway")
    CYCLEWAY("cycleway"),
    @XmlEnumValue("railway")
    RAILWAY("railway");
    private final String value;

    TCrossedElementType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TCrossedElementType fromValue(String v) {
        for (TCrossedElementType c: TCrossedElementType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
