//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDetectorStates.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tDetectorStates"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="inactive"/&gt;
 *     &lt;enumeration value="deactivated"/&gt;
 *     &lt;enumeration value="activated"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tDetectorStates")
@XmlEnum
public enum TDetectorStates {

    @XmlEnumValue("inactive")
    INACTIVE("inactive"),
    @XmlEnumValue("deactivated")
    DEACTIVATED("deactivated"),
    @XmlEnumValue("activated")
    ACTIVATED("activated");
    private final String value;

    TDetectorStates(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TDetectorStates fromValue(String v) {
        for (TDetectorStates c: TDetectorStates.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
