//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDetectorTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tDetectorTypeList"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="weighing"/&gt;
 *     &lt;enumeration value="loadingGauge"/&gt;
 *     &lt;enumeration value="landSlide"/&gt;
 *     &lt;enumeration value="intrusion"/&gt;
 *     &lt;enumeration value="hotWheelBox"/&gt;
 *     &lt;enumeration value="gas"/&gt;
 *     &lt;enumeration value="flatWheel"/&gt;
 *     &lt;enumeration value="fire"/&gt;
 *     &lt;enumeration value="doors"/&gt;
 *     &lt;enumeration value="derailment"/&gt;
 *     &lt;enumeration value="cranks"/&gt;
 *     &lt;enumeration value="avalanche"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tDetectorTypeList")
@XmlEnum
public enum TDetectorTypeList {

    @XmlEnumValue("weighing")
    WEIGHING("weighing"),
    @XmlEnumValue("loadingGauge")
    LOADING_GAUGE("loadingGauge"),
    @XmlEnumValue("landSlide")
    LAND_SLIDE("landSlide"),
    @XmlEnumValue("intrusion")
    INTRUSION("intrusion"),
    @XmlEnumValue("hotWheelBox")
    HOT_WHEEL_BOX("hotWheelBox"),
    @XmlEnumValue("gas")
    GAS("gas"),
    @XmlEnumValue("flatWheel")
    FLAT_WHEEL("flatWheel"),
    @XmlEnumValue("fire")
    FIRE("fire"),
    @XmlEnumValue("doors")
    DOORS("doors"),
    @XmlEnumValue("derailment")
    DERAILMENT("derailment"),
    @XmlEnumValue("cranks")
    CRANKS("cranks"),
    @XmlEnumValue("avalanche")
    AVALANCHE("avalanche");
    private final String value;

    TDetectorTypeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TDetectorTypeList fromValue(String v) {
        for (TDetectorTypeList c: TDetectorTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
