//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tExtentOfControl.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tExtentOfControl"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="steeringOnly"/&gt;
 *     &lt;enumeration value="none"/&gt;
 *     &lt;enumeration value="notificationOnly"/&gt;
 *     &lt;enumeration value="fullControl"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tExtentOfControl")
@XmlEnum
public enum TExtentOfControl {

    @XmlEnumValue("steeringOnly")
    STEERING_ONLY("steeringOnly"),
    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("notificationOnly")
    NOTIFICATION_ONLY("notificationOnly"),
    @XmlEnumValue("fullControl")
    FULL_CONTROL("fullControl");
    private final String value;

    TExtentOfControl(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TExtentOfControl fromValue(String v) {
        for (TExtentOfControl c: TExtentOfControl.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
