//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tGenericRouteTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tGenericRouteTypeList"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="tunnel"/&gt;
 *     &lt;enumeration value="siding"/&gt;
 *     &lt;enumeration value="shunting"/&gt;
 *     &lt;enumeration value="occupied"/&gt;
 *     &lt;enumeration value="normal"/&gt;
 *     &lt;enumeration value="nonElectrified"/&gt;
 *     &lt;enumeration value="callOn"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tGenericRouteTypeList")
@XmlEnum
public enum TGenericRouteTypeList {

    @XmlEnumValue("tunnel")
    TUNNEL("tunnel"),
    @XmlEnumValue("siding")
    SIDING("siding"),
    @XmlEnumValue("shunting")
    SHUNTING("shunting"),
    @XmlEnumValue("occupied")
    OCCUPIED("occupied"),
    @XmlEnumValue("normal")
    NORMAL("normal"),
    @XmlEnumValue("nonElectrified")
    NON_ELECTRIFIED("nonElectrified"),
    @XmlEnumValue("callOn")
    CALL_ON("callOn");
    private final String value;

    TGenericRouteTypeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TGenericRouteTypeList fromValue(String v) {
        for (TGenericRouteTypeList c: TGenericRouteTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
