//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tGradientCurveType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tGradientCurveType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="mixed"/&gt;
 *     &lt;enumeration value="straight"/&gt;
 *     &lt;enumeration value="arc"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tGradientCurveType")
@XmlEnum
public enum TGradientCurveType {


    /**
     * an aggregated curve with arcs and straight parts
     * 
     */
    @XmlEnumValue("mixed")
    MIXED("mixed"),

    /**
     * curve with constant infinite radius (zero curvature)
     * 
     */
    @XmlEnumValue("straight")
    STRAIGHT("straight"),

    /**
     * curve with a constant radius that is not infinite
     * 
     */
    @XmlEnumValue("arc")
    ARC("arc");
    private final String value;

    TGradientCurveType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TGradientCurveType fromValue(String v) {
        for (TGradientCurveType c: TGradientCurveType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
