//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TimePeriodRuleSituation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimePeriodRuleSituation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded"&gt;
 *           &lt;element name="periodRule" type="{https://www.railml.org/schemas/3.1}PeriodRule" minOccurs="0"/&gt;
 *           &lt;element name="publicHolidayPeriodRule" type="{https://www.railml.org/schemas/3.1}PublicHolidayPeriodRule" minOccurs="0"/&gt;
 *           &lt;element name="elementBasedPeriodRule" type="{https://www.railml.org/schemas/3.1}ElemBasedPeriodRule" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="fromDate" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimePeriodRuleSituation", propOrder = {
    "periodRuleOrPublicHolidayPeriodRuleOrElementBasedPeriodRule"
})
public class TimePeriodRuleSituation {

    @XmlElements({
        @XmlElement(name = "periodRule", type = PeriodRule.class),
        @XmlElement(name = "publicHolidayPeriodRule", type = PublicHolidayPeriodRule.class),
        @XmlElement(name = "elementBasedPeriodRule", type = ElemBasedPeriodRule.class)
    })
    protected List<TimePeriodRule> periodRuleOrPublicHolidayPeriodRuleOrElementBasedPeriodRule;
    @XmlAttribute(name = "fromDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fromDate;

    /**
     * Gets the value of the periodRuleOrPublicHolidayPeriodRuleOrElementBasedPeriodRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the periodRuleOrPublicHolidayPeriodRuleOrElementBasedPeriodRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeriodRuleOrPublicHolidayPeriodRuleOrElementBasedPeriodRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PeriodRule }
     * {@link PublicHolidayPeriodRule }
     * {@link ElemBasedPeriodRule }
     * 
     * 
     */
    public List<TimePeriodRule> getPeriodRuleOrPublicHolidayPeriodRuleOrElementBasedPeriodRule() {
        if (periodRuleOrPublicHolidayPeriodRuleOrElementBasedPeriodRule == null) {
            periodRuleOrPublicHolidayPeriodRuleOrElementBasedPeriodRule = new ArrayList<TimePeriodRule>();
        }
        return this.periodRuleOrPublicHolidayPeriodRuleOrElementBasedPeriodRule;
    }

    /**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFromDate(XMLGregorianCalendar value) {
        this.fromDate = value;
    }

}
