//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tJointsType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tJointsType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="glued"/&gt;
 *     &lt;enumeration value="insulated"/&gt;
 *     &lt;enumeration value="welded"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tJointsType")
@XmlEnum
public enum TJointsType {

    @XmlEnumValue("glued")
    GLUED("glued"),
    @XmlEnumValue("insulated")
    INSULATED("insulated"),
    @XmlEnumValue("welded")
    WELDED("welded");
    private final String value;

    TJointsType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TJointsType fromValue(String v) {
        for (TJointsType c: TJointsType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
