//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tLevelCrossingActivation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tLevelCrossingActivation"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="trainAutomatic"/&gt;
 *     &lt;enumeration value="trainManual"/&gt;
 *     &lt;enumeration value="infrastructureAutomatic"/&gt;
 *     &lt;enumeration value="infrastructureManual"/&gt;
 *     &lt;enumeration value="none"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tLevelCrossingActivation")
@XmlEnum
public enum TLevelCrossingActivation {


    /**
     * level crossing is activated automatically from train side
     * 
     */
    @XmlEnumValue("trainAutomatic")
    TRAIN_AUTOMATIC("trainAutomatic"),

    /**
     * level crossing is activated manually from train side (action of train driver required)
     * 
     */
    @XmlEnumValue("trainManual")
    TRAIN_MANUAL("trainManual"),

    /**
     * level crossing is activated automatically from infrastructure side (e.g. via activating rail detector)
     * 
     */
    @XmlEnumValue("infrastructureAutomatic")
    INFRASTRUCTURE_AUTOMATIC("infrastructureAutomatic"),

    /**
     * level crossing is activated manually from infrastructure side (e.g. by a dispatcher)
     * 
     */
    @XmlEnumValue("infrastructureManual")
    INFRASTRUCTURE_MANUAL("infrastructureManual"),

    /**
     * there is no activation of the level crossing protection
     * 
     */
    @XmlEnumValue("none")
    NONE("none");
    private final String value;

    TLevelCrossingActivation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TLevelCrossingActivation fromValue(String v) {
        for (TLevelCrossingActivation c: TLevelCrossingActivation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
