//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tLineTrafficCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tLineTrafficCode"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="F1600"/&gt;
 *     &lt;enumeration value="F1520"/&gt;
 *     &lt;enumeration value="F4"/&gt;
 *     &lt;enumeration value="F3"/&gt;
 *     &lt;enumeration value="F2"/&gt;
 *     &lt;enumeration value="F1"/&gt;
 *     &lt;enumeration value="P1600"/&gt;
 *     &lt;enumeration value="P1520"/&gt;
 *     &lt;enumeration value="P6"/&gt;
 *     &lt;enumeration value="P5"/&gt;
 *     &lt;enumeration value="P4"/&gt;
 *     &lt;enumeration value="P3"/&gt;
 *     &lt;enumeration value="P2"/&gt;
 *     &lt;enumeration value="P1"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tLineTrafficCode")
@XmlEnum
public enum TLineTrafficCode {

    @XmlEnumValue("F1600")
    F_1600("F1600"),
    @XmlEnumValue("F1520")
    F_1520("F1520"),
    @XmlEnumValue("F4")
    F_4("F4"),
    @XmlEnumValue("F3")
    F_3("F3"),
    @XmlEnumValue("F2")
    F_2("F2"),
    @XmlEnumValue("F1")
    F_1("F1"),
    @XmlEnumValue("P1600")
    P_1600("P1600"),
    @XmlEnumValue("P1520")
    P_1520("P1520"),
    @XmlEnumValue("P6")
    P_6("P6"),
    @XmlEnumValue("P5")
    P_5("P5"),
    @XmlEnumValue("P4")
    P_4("P4"),
    @XmlEnumValue("P3")
    P_3("P3"),
    @XmlEnumValue("P2")
    P_2("P2"),
    @XmlEnumValue("P1")
    P_1("P1");
    private final String value;

    TLineTrafficCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TLineTrafficCode fromValue(String v) {
        for (TLineTrafficCode c: TLineTrafficCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
