//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tOperationalTrainType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tOperationalTrainType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="all"/&gt;
 *     &lt;enumeration value="highspeed"/&gt;
 *     &lt;enumeration value="freight"/&gt;
 *     &lt;enumeration value="passenger"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tOperationalTrainType")
@XmlEnum
public enum TOperationalTrainType {

    @XmlEnumValue("all")
    ALL("all"),
    @XmlEnumValue("highspeed")
    HIGHSPEED("highspeed"),
    @XmlEnumValue("freight")
    FREIGHT("freight"),
    @XmlEnumValue("passenger")
    PASSENGER("passenger");
    private final String value;

    TOperationalTrainType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TOperationalTrainType fromValue(String v) {
        for (TOperationalTrainType c: TOperationalTrainType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
