//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This is the top level element for railML3 topology model.
 * 
 * <p>Java class for Topology complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Topology"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="netElements" type="{https://www.railml.org/schemas/3.1}NetElements"/&gt;
 *         &lt;element name="netRelations" type="{https://www.railml.org/schemas/3.1}NetRelations" minOccurs="0"/&gt;
 *         &lt;element name="networks" type="{https://www.railml.org/schemas/3.1}Networks"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Topology", propOrder = {
    "netElements",
    "netRelations",
    "networks"
})
public class Topology {

    @XmlElement(required = true)
    protected NetElements netElements;
    protected NetRelations netRelations;
    @XmlElement(required = true)
    protected Networks networks;

    /**
     * Gets the value of the netElements property.
     * 
     * @return
     *     possible object is
     *     {@link NetElements }
     *     
     */
    public NetElements getNetElements() {
        return netElements;
    }

    /**
     * Sets the value of the netElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetElements }
     *     
     */
    public void setNetElements(NetElements value) {
        this.netElements = value;
    }

    /**
     * Gets the value of the netRelations property.
     * 
     * @return
     *     possible object is
     *     {@link NetRelations }
     *     
     */
    public NetRelations getNetRelations() {
        return netRelations;
    }

    /**
     * Sets the value of the netRelations property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetRelations }
     *     
     */
    public void setNetRelations(NetRelations value) {
        this.netRelations = value;
    }

    /**
     * Gets the value of the networks property.
     * 
     * @return
     *     possible object is
     *     {@link Networks }
     *     
     */
    public Networks getNetworks() {
        return networks;
    }

    /**
     * Sets the value of the networks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Networks }
     *     
     */
    public void setNetworks(Networks value) {
        this.networks = value;
    }

}
