//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrackBed complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrackBed"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}FunctionalInfrastructureEntity"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{https://www.railml.org/schemas/3.1}aTrackbed"/&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrackBed")
public class TrackBed
    extends FunctionalInfrastructureEntity
{

    @XmlAttribute(name = "ballastType")
    protected TBallastType ballastType;
    @XmlAttribute(name = "railType")
    protected String railType;
    @XmlAttribute(name = "sleepersType")
    protected TSleepersType sleepersType;
    @XmlAttribute(name = "jointsType")
    protected TJointsType jointsType;

    /**
     * Gets the value of the ballastType property.
     * 
     * @return
     *     possible object is
     *     {@link TBallastType }
     *     
     */
    public TBallastType getBallastType() {
        return ballastType;
    }

    /**
     * Sets the value of the ballastType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBallastType }
     *     
     */
    public void setBallastType(TBallastType value) {
        this.ballastType = value;
    }

    /**
     * Gets the value of the railType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRailType() {
        return railType;
    }

    /**
     * Sets the value of the railType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRailType(String value) {
        this.railType = value;
    }

    /**
     * Gets the value of the sleepersType property.
     * 
     * @return
     *     possible object is
     *     {@link TSleepersType }
     *     
     */
    public TSleepersType getSleepersType() {
        return sleepersType;
    }

    /**
     * Sets the value of the sleepersType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSleepersType }
     *     
     */
    public void setSleepersType(TSleepersType value) {
        this.sleepersType = value;
    }

    /**
     * Gets the value of the jointsType property.
     * 
     * @return
     *     possible object is
     *     {@link TJointsType }
     *     
     */
    public TJointsType getJointsType() {
        return jointsType;
    }

    /**
     * Sets the value of the jointsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TJointsType }
     *     
     */
    public void setJointsType(TJointsType value) {
        this.jointsType = value;
    }

}
