//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrainRadio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrainRadio"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}FunctionalInfrastructureEntity"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="supportsBroadcastCalls" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="supportsDirectMode" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="supportsPublicEmergency" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="supportsPublicNetworkRoaming" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="radioSystem" type="{https://www.railml.org/schemas/3.1}tTrainRadioSystemExt" /&gt;
 *       &lt;attribute name="supportsTextMessageService" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="networkSelection" type="{https://www.railml.org/schemas/3.1}tTrainRadioNetworkSelectionExt" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrainRadio")
public class TrainRadio
    extends FunctionalInfrastructureEntity
{

    @XmlAttribute(name = "supportsBroadcastCalls")
    protected Boolean supportsBroadcastCalls;
    @XmlAttribute(name = "supportsDirectMode")
    protected Boolean supportsDirectMode;
    @XmlAttribute(name = "supportsPublicEmergency")
    protected Boolean supportsPublicEmergency;
    @XmlAttribute(name = "supportsPublicNetworkRoaming")
    protected Boolean supportsPublicNetworkRoaming;
    @XmlAttribute(name = "radioSystem")
    protected String radioSystem;
    @XmlAttribute(name = "supportsTextMessageService")
    protected Boolean supportsTextMessageService;
    @XmlAttribute(name = "networkSelection")
    protected String networkSelection;

    /**
     * Gets the value of the supportsBroadcastCalls property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSupportsBroadcastCalls() {
        return supportsBroadcastCalls;
    }

    /**
     * Sets the value of the supportsBroadcastCalls property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSupportsBroadcastCalls(Boolean value) {
        this.supportsBroadcastCalls = value;
    }

    /**
     * Gets the value of the supportsDirectMode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSupportsDirectMode() {
        return supportsDirectMode;
    }

    /**
     * Sets the value of the supportsDirectMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSupportsDirectMode(Boolean value) {
        this.supportsDirectMode = value;
    }

    /**
     * Gets the value of the supportsPublicEmergency property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSupportsPublicEmergency() {
        return supportsPublicEmergency;
    }

    /**
     * Sets the value of the supportsPublicEmergency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSupportsPublicEmergency(Boolean value) {
        this.supportsPublicEmergency = value;
    }

    /**
     * Gets the value of the supportsPublicNetworkRoaming property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSupportsPublicNetworkRoaming() {
        return supportsPublicNetworkRoaming;
    }

    /**
     * Sets the value of the supportsPublicNetworkRoaming property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSupportsPublicNetworkRoaming(Boolean value) {
        this.supportsPublicNetworkRoaming = value;
    }

    /**
     * Gets the value of the radioSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadioSystem() {
        return radioSystem;
    }

    /**
     * Sets the value of the radioSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadioSystem(String value) {
        this.radioSystem = value;
    }

    /**
     * Gets the value of the supportsTextMessageService property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSupportsTextMessageService() {
        return supportsTextMessageService;
    }

    /**
     * Sets the value of the supportsTextMessageService property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSupportsTextMessageService(Boolean value) {
        this.supportsTextMessageService = value;
    }

    /**
     * Gets the value of the networkSelection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkSelection() {
        return networkSelection;
    }

    /**
     * Sets the value of the networkSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkSelection(String value) {
        this.networkSelection = value;
    }

}
