//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tRouteConflictTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tRouteConflictTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="overlappingTVDsection"/&gt;
 *     &lt;enumeration value="conflictingSwitchPosition"/&gt;
 *     &lt;enumeration value="conflictingStatus"/&gt;
 *     &lt;enumeration value="conflictingOverlap"/&gt;
 *     &lt;enumeration value="conflictingHeadProtection"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tRouteConflictTypes")
@XmlEnum
public enum TRouteConflictTypes {

    @XmlEnumValue("overlappingTVDsection")
    OVERLAPPING_TV_DSECTION("overlappingTVDsection"),
    @XmlEnumValue("conflictingSwitchPosition")
    CONFLICTING_SWITCH_POSITION("conflictingSwitchPosition"),
    @XmlEnumValue("conflictingStatus")
    CONFLICTING_STATUS("conflictingStatus"),
    @XmlEnumValue("conflictingOverlap")
    CONFLICTING_OVERLAP("conflictingOverlap"),
    @XmlEnumValue("conflictingHeadProtection")
    CONFLICTING_HEAD_PROTECTION("conflictingHeadProtection");
    private final String value;

    TRouteConflictTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TRouteConflictTypes fromValue(String v) {
        for (TRouteConflictTypes c: TRouteConflictTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
