//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tSignalLevelCrossingType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tSignalLevelCrossingType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="supervision"/&gt;
 *     &lt;enumeration value="activating"/&gt;
 *     &lt;enumeration value="announcing"/&gt;
 *     &lt;enumeration value="whistle"/&gt;
 *     &lt;enumeration value="bell"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tSignalLevelCrossingType")
@XmlEnum
public enum TSignalLevelCrossingType {


    /**
     * final level crossing supervision signal that is located immediately before the level crossing.
     * 
     */
    @XmlEnumValue("supervision")
    SUPERVISION("supervision"),

    /**
     * Notice (board) indicating the activation point at technically secured level crossings (with warning light and/or barrier).
     * 
     */
    @XmlEnumValue("activating")
    ACTIVATING("activating"),

    /**
     * Announcement signal which indicates the state of the technical safety at technically secured level crossings (with warning light and/or barrier).
     * 
     */
    @XmlEnumValue("announcing")
    ANNOUNCING("announcing"),

    /**
     * Whistle board, as a command to the driver to activate the engine whistle.
     * 
     */
    @XmlEnumValue("whistle")
    WHISTLE("whistle"),

    /**
     * Bell board as a request to the driver to switch on the engine bell
     * 
     */
    @XmlEnumValue("bell")
    BELL("bell");
    private final String value;

    TSignalLevelCrossingType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TSignalLevelCrossingType fromValue(String v) {
        for (TSignalLevelCrossingType c: TSignalLevelCrossingType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
