//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tSignalFunctionList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tSignalFunctionList"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="main"/&gt;
 *     &lt;enumeration value="repeater"/&gt;
 *     &lt;enumeration value="distant"/&gt;
 *     &lt;enumeration value="shunting"/&gt;
 *     &lt;enumeration value="barrage"/&gt;
 *     &lt;enumeration value="block"/&gt;
 *     &lt;enumeration value="junction"/&gt;
 *     &lt;enumeration value="exit"/&gt;
 *     &lt;enumeration value="intermediateStop"/&gt;
 *     &lt;enumeration value="intermediate"/&gt;
 *     &lt;enumeration value="entry"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tSignalFunctionList")
@XmlEnum
public enum TSignalFunctionList {

    @XmlEnumValue("main")
    MAIN("main"),
    @XmlEnumValue("repeater")
    REPEATER("repeater"),
    @XmlEnumValue("distant")
    DISTANT("distant"),
    @XmlEnumValue("shunting")
    SHUNTING("shunting"),
    @XmlEnumValue("barrage")
    BARRAGE("barrage"),
    @XmlEnumValue("block")
    BLOCK("block"),
    @XmlEnumValue("junction")
    JUNCTION("junction"),
    @XmlEnumValue("exit")
    EXIT("exit"),
    @XmlEnumValue("intermediateStop")
    INTERMEDIATE_STOP("intermediateStop"),
    @XmlEnumValue("intermediate")
    INTERMEDIATE("intermediate"),
    @XmlEnumValue("entry")
    ENTRY("entry");
    private final String value;

    TSignalFunctionList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TSignalFunctionList fromValue(String v) {
        for (TSignalFunctionList c: TSignalFunctionList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
