//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tTrainDetectionElementType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tTrainDetectionElementType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="axleCounter"/&gt;
 *     &lt;enumeration value="axleCountingCircuit"/&gt;
 *     &lt;enumeration value="clearancePoint"/&gt;
 *     &lt;enumeration value="insulatedRailJoint"/&gt;
 *     &lt;enumeration value="trackCircuit"/&gt;
 *     &lt;enumeration value="virtualClearancePoint"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tTrainDetectionElementType")
@XmlEnum
public enum TTrainDetectionElementType {

    @XmlEnumValue("axleCounter")
    AXLE_COUNTER("axleCounter"),
    @XmlEnumValue("axleCountingCircuit")
    AXLE_COUNTING_CIRCUIT("axleCountingCircuit"),
    @XmlEnumValue("clearancePoint")
    CLEARANCE_POINT("clearancePoint"),
    @XmlEnumValue("insulatedRailJoint")
    INSULATED_RAIL_JOINT("insulatedRailJoint"),
    @XmlEnumValue("trackCircuit")
    TRACK_CIRCUIT("trackCircuit"),
    @XmlEnumValue("virtualClearancePoint")
    VIRTUAL_CLEARANCE_POINT("virtualClearancePoint");
    private final String value;

    TTrainDetectionElementType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTrainDetectionElementType fromValue(String v) {
        for (TTrainDetectionElementType c: TTrainDetectionElementType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
