//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tTrainRadioSystem.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tTrainRadioSystem"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="analogDistantRadio"/&gt;
 *     &lt;enumeration value="analogLocalRadio"/&gt;
 *     &lt;enumeration value="otherDigitalRadio"/&gt;
 *     &lt;enumeration value="GSM-R"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tTrainRadioSystem")
@XmlEnum
public enum TTrainRadioSystem {

    @XmlEnumValue("analogDistantRadio")
    ANALOG_DISTANT_RADIO("analogDistantRadio"),
    @XmlEnumValue("analogLocalRadio")
    ANALOG_LOCAL_RADIO("analogLocalRadio"),
    @XmlEnumValue("otherDigitalRadio")
    OTHER_DIGITAL_RADIO("otherDigitalRadio"),
    @XmlEnumValue("GSM-R")
    GSM_R("GSM-R");
    private final String value;

    TTrainRadioSystem(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTrainRadioSystem fromValue(String v) {
        for (TTrainRadioSystem c: TTrainRadioSystem.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
