//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tTSIPantoHeadType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tTSIPantoHeadType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="none"/&gt;
 *     &lt;enumeration value="tsi2000_2260"/&gt;
 *     &lt;enumeration value="tsi1600"/&gt;
 *     &lt;enumeration value="tsi1950"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tTSIPantoHeadType")
@XmlEnum
public enum TTSIPantoHeadType {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("tsi2000_2260")
    TSI_2000_2260("tsi2000_2260"),
    @XmlEnumValue("tsi1600")
    TSI_1600("tsi1600"),
    @XmlEnumValue("tsi1950")
    TSI_1950("tsi1950");
    private final String value;

    TTSIPantoHeadType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTSIPantoHeadType fromValue(String v) {
        for (TTSIPantoHeadType c: TTSIPantoHeadType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
