//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * A track vacancy detection (TVD) section reports train occupancy to the interlocking. This is a logical unit characterised by the delimiters of the section. Typically, a section is delimited by two insulated track joints or axle counters at the extremities. Sections with a switch or a crossing can have several such limits.
 * 
 * <p>Java class for TvdSection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TvdSection"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}TrackAsset"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="hasDemarcatingBufferstop" type="{https://www.railml.org/schemas/3.1}EntityILref" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="hasExitSignal" type="{https://www.railml.org/schemas/3.1}EntityILref" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="hasDemarcatingTraindetector" type="{https://www.railml.org/schemas/3.1}EntityILref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="hasResetStrategy" type="{https://www.railml.org/schemas/3.1}EntityILref" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="isBerthingTrack" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="residualRouteCancellationDelay" use="required" type="{http://www.w3.org/2001/XMLSchema}duration" /&gt;
 *       &lt;attribute name="partialRouteReleaseDelay" use="required" type="{http://www.w3.org/2001/XMLSchema}duration" /&gt;
 *       &lt;attribute name="technology" type="{https://www.railml.org/schemas/3.1}tTvdSectionTechnologyTypeExt" /&gt;
 *       &lt;attribute name="frequency" type="{https://www.railml.org/schemas/3.1}tFrequencyHertz" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TvdSection", propOrder = {
    "hasDemarcatingBufferstop",
    "hasExitSignal",
    "hasDemarcatingTraindetector",
    "hasResetStrategy"
})
public class TvdSection
    extends TrackAsset
{

    protected List<EntityILref> hasDemarcatingBufferstop;
    protected List<EntityILref> hasExitSignal;
    protected List<EntityILref> hasDemarcatingTraindetector;
    protected EntityILref hasResetStrategy;
    @XmlAttribute(name = "isBerthingTrack")
    protected Boolean isBerthingTrack;
    @XmlAttribute(name = "residualRouteCancellationDelay", required = true)
    protected Duration residualRouteCancellationDelay;
    @XmlAttribute(name = "partialRouteReleaseDelay", required = true)
    protected Duration partialRouteReleaseDelay;
    @XmlAttribute(name = "technology")
    protected String technology;
    @XmlAttribute(name = "frequency")
    protected BigDecimal frequency;

    /**
     * Gets the value of the hasDemarcatingBufferstop property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hasDemarcatingBufferstop property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHasDemarcatingBufferstop().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getHasDemarcatingBufferstop() {
        if (hasDemarcatingBufferstop == null) {
            hasDemarcatingBufferstop = new ArrayList<EntityILref>();
        }
        return this.hasDemarcatingBufferstop;
    }

    /**
     * Gets the value of the hasExitSignal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hasExitSignal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHasExitSignal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getHasExitSignal() {
        if (hasExitSignal == null) {
            hasExitSignal = new ArrayList<EntityILref>();
        }
        return this.hasExitSignal;
    }

    /**
     * Gets the value of the hasDemarcatingTraindetector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hasDemarcatingTraindetector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHasDemarcatingTraindetector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getHasDemarcatingTraindetector() {
        if (hasDemarcatingTraindetector == null) {
            hasDemarcatingTraindetector = new ArrayList<EntityILref>();
        }
        return this.hasDemarcatingTraindetector;
    }

    /**
     * Gets the value of the hasResetStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link EntityILref }
     *     
     */
    public EntityILref getHasResetStrategy() {
        return hasResetStrategy;
    }

    /**
     * Sets the value of the hasResetStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityILref }
     *     
     */
    public void setHasResetStrategy(EntityILref value) {
        this.hasResetStrategy = value;
    }

    /**
     * Gets the value of the isBerthingTrack property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsBerthingTrack() {
        return isBerthingTrack;
    }

    /**
     * Sets the value of the isBerthingTrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBerthingTrack(Boolean value) {
        this.isBerthingTrack = value;
    }

    /**
     * Gets the value of the residualRouteCancellationDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getResidualRouteCancellationDelay() {
        return residualRouteCancellationDelay;
    }

    /**
     * Sets the value of the residualRouteCancellationDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setResidualRouteCancellationDelay(Duration value) {
        this.residualRouteCancellationDelay = value;
    }

    /**
     * Gets the value of the partialRouteReleaseDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getPartialRouteReleaseDelay() {
        return partialRouteReleaseDelay;
    }

    /**
     * Sets the value of the partialRouteReleaseDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setPartialRouteReleaseDelay(Duration value) {
        this.partialRouteReleaseDelay = value;
    }

    /**
     * Gets the value of the technology property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnology() {
        return technology;
    }

    /**
     * Sets the value of the technology property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnology(String value) {
        this.technology = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFrequency(BigDecimal value) {
        this.frequency = value;
    }

}
