//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//


package https.www_railml_org.schemas._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Visualization complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Visualization"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.1}VisualizationBaseElement"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="spotElementProjection" type="{https://www.railml.org/schemas/3.1}SpotProjection" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="linearElementProjection" type="{https://www.railml.org/schemas/3.1}LinearProjection" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="areaElementProjection" type="{https://www.railml.org/schemas/3.1}AreaProjection" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="positioningSystemRef" type="{https://www.railml.org/schemas/3.1}tRef" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Visualization", propOrder = {
    "spotElementProjection",
    "linearElementProjection",
    "areaElementProjection"
})
public class Visualization
    extends VisualizationBaseElement
{

    protected List<SpotProjection> spotElementProjection;
    protected List<LinearProjection> linearElementProjection;
    protected List<AreaProjection> areaElementProjection;
    @XmlAttribute(name = "positioningSystemRef")
    protected String positioningSystemRef;

    /**
     * Gets the value of the spotElementProjection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spotElementProjection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpotElementProjection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpotProjection }
     * 
     * 
     */
    public List<SpotProjection> getSpotElementProjection() {
        if (spotElementProjection == null) {
            spotElementProjection = new ArrayList<SpotProjection>();
        }
        return this.spotElementProjection;
    }

    /**
     * Gets the value of the linearElementProjection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linearElementProjection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinearElementProjection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinearProjection }
     * 
     * 
     */
    public List<LinearProjection> getLinearElementProjection() {
        if (linearElementProjection == null) {
            linearElementProjection = new ArrayList<LinearProjection>();
        }
        return this.linearElementProjection;
    }

    /**
     * Gets the value of the areaElementProjection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the areaElementProjection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAreaElementProjection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AreaProjection }
     * 
     * 
     */
    public List<AreaProjection> getAreaElementProjection() {
        if (areaElementProjection == null) {
            areaElementProjection = new ArrayList<AreaProjection>();
        }
        return this.areaElementProjection;
    }

    /**
     * Gets the value of the positioningSystemRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositioningSystemRef() {
        return positioningSystemRef;
    }

    /**
     * Sets the value of the positioningSystemRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositioningSystemRef(String value) {
        this.positioningSystemRef = value;
    }

}
