//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 02:41:02 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.railml.org/schemas/3.1/gml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.www_railml_org.schemas._3_1.gml;
